[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  # Environment variables for Supabase
  # Note: These should be set in Netlify dashboard under Site settings > Environment variables
  # NEXT_PUBLIC_SUPABASE_URL = "your-supabase-url"
  # NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-supabase-anon-key"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"
