[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  # Netlify will automatically inject environment variables set in the dashboard
  # Make sure to set these in Site settings > Environment variables:
  # NEXT_PUBLIC_SUPABASE_URL = "https://rasqxsyaqqboilmajvbu.supabase.co"
  # NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-anon-key-here"

# Enable the Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Context-specific deployments
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"
